// Generated by https://quicktype.io

export interface Resume {
  id: string;
  appliedFor: CompanyApplication;
  basics: ResumeBasics;
  work: ResumeWorkExperience[];
  volunteer: ResumeWorkExperience[];
  education: ResumeEducation[];
  awards: Award[];
  publications: Publication[];
  skills: ResumeSkill[];
  languages: ResumeLanguage[];
  interests: ResumeInterest[];
  references: ResumeReference[];
}

export interface CompanyApplication {
  companyName: string;
  dateApplied: string;
}

export interface Award {
  title: string;
  date: string;
  awarder: string;
  summary: string;
}

export interface ResumeBasics {
  name: string;
  label: string;
  picture: string;
  email: string;
  phone: string;
  website: string;
  summary: string;
  objective: string;
  location: ResumeBasicsLocation;
  profiles: ResumeBasicsProfile[];
}

export interface ResumeBasicsLocation {
  address: string;
  postalCode: string;
  city: string;
  countryCode: string;
  region: string;
}

export interface ResumeBasicsProfile {
  network: string;
  username: string;
  url: string;
}

export interface ResumeEducation {
  institution: string;
  area: string;
  studyType: string;
  startDate: string;
  endDate: string;
  gpa: string;
  courses: string[];
}

export interface ResumeInterest {
  name: string;
  keywords: string[];
}

export interface ResumeLanguage {
  language: string;
  fluency: string;
}

export interface Publication {
  name: string;
  publisher: string;
  releaseDate: string;
  website: string;
  summary: string;
}

export interface ResumeReference {
  name: string;
  reference: string;
}

export interface ResumeSkill {
  name: string;
  level: string;
  lastUsed: string;
  keywords: string[];
}

export interface ResumeWorkExperience {
  organization?: string;
  position: string;
  website: string;
  startDate: string;
  endDate: string;
  summary: string;
  highlights: string[];
  company?: string;
}

export interface Customer {
  id: string;
  resumes: Resume[];
}
