// Generated by https://quicktype.io

export interface Resume {
  id: string;
  basics:       ResumeBasics;
  work:         WorkExperience[];
  volunteer:    WorkExperience[];
  education:    Education[];
  awards:       Award[];
  publications: Publication[];
  skills:       Skill[];
  languages:    Language[];
  interests:    Interest[];
  references:   Reference[];
}

export interface Award {
  title:   string;
  date:    string;
  awarder: string;
  summary: string;
}

export interface ResumeBasics {
  name:     string;
  label:    string;
  picture:  string;
  email:    string;
  phone:    string;
  website:  string;
  summary:  string;
  location: ResumeBasicsLocation;
  profiles: ResumeBasicsProfile[];
}

export interface ResumeBasicsLocation {
  address:     string;
  postalCode:  string;
  city:        string;
  countryCode: string;
  region:      string;
}

export interface ResumeBasicsProfile {
  network:  string;
  username: string;
  url:      string;
}

export interface Education {
  institution: string;
  area:        string;
  studyType:   string;
  startDate:   string;
  endDate:     string;
  gpa:         string;
  courses:     string[];
}

export interface Interest {
  name:     string;
  keywords: string[];
}

export interface Language {
  language: string;
  fluency:  string;
}

export interface Publication {
  name:        string;
  publisher:   string;
  releaseDate: string;
  website:     string;
  summary:     string;
}

export interface Reference {
  name:      string;
  reference: string;
}

export interface Skill {
  name:     string;
  level:    string;
  keywords: string[];
}

export interface WorkExperience {
  organization?: string;
  position:      string;
  website:       string;
  startDate:     string;
  endDate:       string;
  summary:       string;
  highlights:    string[];
  company?:      string;
}

export interface Customer {
  id: string;
  resumes: Resume[];
}
